remote_smtp_brevo:
  driver = smtp
  port = 587
  hosts_require_tls = smtp-relay.brevo.com
  hosts_require_auth = smtp-relay.brevo.com
  interface = <; ${if exists{/etc/virtual/domainips}{${lookup{$sender_address_domain}lsearch*{/etc/virtual/domainips}}}}
  helo_data = ${if exists{/etc/virtual/helo_data}{${lookup{$sending_ip_address}iplsearch{/etc/virtual/helo_data}{$value}{$primary_hostname}}}{$primary_hostname}}
